import type { Metadata } from 'next'
import { noto } from './fonts'
import './globals.css'
import Script from 'next/script'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en-US">
      <body className={`language-en_US ${noto.variable} antialiased`}>
        {children}
        <Script id="vtoLoader" src="/vto-lazy-loader.js" strategy="afterInteractive" />
      </body>
    </html>
  )
}
